---
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
branches:
  only:
    - master
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
before_build:
  - nuget update -self
  - nuget restore
test_script:
  - dotnet test .\ElGamalTests\ElGamalTests.csproj --no-build
configuration: Release
image: "Visual Studio 2017 Preview"
nuget:
  disable_publish_on_pr: true
cache:
  - packages
environment:
  AppVeyorAPIToken:
    secure: GvygCCndEp8eiXvItooIyglWYnyfUvg4YNyaufw3N3A=
  AppVeyorGlobalAPIToken:
    secure: XaWtuymf7dtXgjvEdnxXZVuIGVwMYUqOcE3dl3f3JzA=
version: "0.10.0.{build}"